server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: entrega-service
              uri: https://localhost:7158
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0

            - id: comanda-service
              uri: https://localhost:8485
              predicates:
                - Path=/api/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          httpclient:
            ssl:
              use-insecure-trust-manager: true
