spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: entrega-service
              uri: https://localhost:7158
              predicates:
                - Path=/entrega/**
              filters:
                - StripPrefix=1

            - id: comanda-service
              uri: https://localhost:8485
              predicates:
                - Path=/comanda/**
              filters:
                - StripPrefix=1

            - id: cozinha-service
              uri: http://localhost:9090
              predicates:
                - Path=/cozinha/**
              filters:
                - StripPrefix=1
          httpclient:
            ssl:
              use-insecure-trust-manager: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

server:
  port: 8081
