spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: entrega-service
              uri: https://localhost:7158
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0
            - id: comanda-service
              uri: https://localhost:8485
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0
            - id: cozinha-service
              uri: http://localhost:9090
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1
                -
          httpclient:
            ssl:
              use-insecure-trust-manager: true

server:
  port: 8081
