// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_entregas.Data;

#nullable disable

namespace api_entregas.Migrations
{
    [DbContext(typeof(EntregaDbContext))]
    [Migration("20250717180242_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("api_entregas.Models.Entrega", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSolicitada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotoboyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotoboyId");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("api_entregas.Models.Motoboy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacaMoto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Motoboys");
                });

            modelBuilder.Entity("api_entregas.Models.Entrega", b =>
                {
                    b.HasOne("api_entregas.Models.Motoboy", "Motoboy")
                        .WithMany("Entregas")
                        .HasForeignKey("MotoboyId");

                    b.Navigation("Motoboy");
                });

            modelBuilder.Entity("api_entregas.Models.Motoboy", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
